Gzip request and response support
CadentTech/porter pull request #44
Opened 2020-10-07 17:35 UTC by cadent-mrichman

This PR adds support for gzip compression of request and response data.

* Request data will be decompressed if the header `Content-Encoding: gzip` is found.
* Response data will be compressed if the header `Accept-Encoding: gzip` is found **and** `porter.config.support_gzip` is set to true.

2020-10-07 18:37 UTC, cadent-dgates commented on porter/api.py
> +        silent (bool): Silence parsing errors and return None instead.
Nice keyword for a wrapper

2020-10-07 18:51 UTC, cadent-dgates requested changes
@cadent-mrichman Still need to review the tests, but I started a preliminary review.

One additional thing I couldn't comment on, I believe we should modify BaseService._default_response_schemas to account for UnsupportedMediaType error now raised by request_json().

2020-10-07 18:51 UTC, cadent-dgates commented on porter/api.py
> +            return json.loads(gzip.decompress(request.get_data()).decode('utf-8'))
Can we refactor this to a single return?

2020-10-07 18:51 UTC, cadent-dgates commented on porter/api.py
> +        if not silent:
What's the use case for ignoring an error here?

2020-10-07 18:51 UTC, cadent-dgates commented on porter/api.py
> +        if not silent:
Refactor this with the return statements above. I'd prefer a more explicit check before raising an exception rather than an implicit "if we get this far there must be an error"

2020-10-07 18:51 UTC, cadent-dgates commented on porter/api.py
> +        # If the client requests an unsupported encoding,
good thinking, this is probably better than a 406

2020-10-07 18:51 UTC, cadent-dgates commented on porter/api.py
> +        _gzip_response(response)
Rather than modifying the response in place, do you think it makes sense to add this as a method on the response object?

2020-10-07 18:51 UTC, cadent-dgates commented on tests/test_app.py
> +                'description': '<div></div><div><p>(porter v0.15.2)</p></div>',
wouldn't this actually get bumped to 0.15.3?

2020-10-07 18:59 UTC, cadent-mrichman commented on porter/api.py
> +        if not silent:
It's used by `response.make_error_response()` if `return_user_data_on_error`.

2020-10-07 19:03 UTC, cadent-dgates requested changes

2020-10-07 19:03 UTC, cadent-dgates commented on tests/test_api.py
> +        """Pass thru if no compression requested."""
Depending on whether or not we refactor _gzip_response, I might rethink exactly what these tests are doing

2020-10-07 19:06 UTC, cadent-dgates commented on porter/api.py
> +        if not silent:
ah okay, I see

2020-10-07 20:14 UTC, cadent-mrichman commented on tests/test_app.py
> +                'description': '<div></div><div><p>(porter v0.15.2)</p></div>',
Presumably, yes -- this change just caught the test up with the version bump from the previous release.

2020-10-08 16:27 UTC, cadent-mrichman commented on porter/api.py
> +        _gzip_response(response)
Noting for the record that we discussed this offline and decided to refactor.

2020-10-08 16:27 UTC, cadent-mrichman commented on tests/test_app.py
> +                'description': '<div></div><div><p>(porter v0.15.2)</p></div>',
Bumped to 0.15.3 in a recent commit.

2020-10-08 16:28 UTC, cadent-mrichman commented on tests/test_api.py
> +        with mock.patch('flask.request', test_request(self.valid_bytes, None)):
In a recent commit, I didn't split every single assertion, but did split up logically distinct tests.

2020-10-08 16:35 UTC, cadent-mrichman commented on porter/api.py
> +            return json.loads(gzip.decompress(request.get_data()).decode('utf-8'))
Refactored in a recent commit.

2020-10-12 15:31 UTC, cadent-dgates commented on porter/api.py
> +        if not silent:
I think the implementation would be cleaner here if we had just one try-except block. Something like

```python
try:
    if encoding == 'gzip:
        ...
    elif ...
    else ...
except Exception as err:
    if not silent:
        raise err
```

Also we should catch explicit exceptions here. Definitely need to replace `except:` in the current implementation and even `except Exception` in my example is probably too broad

2020-10-12 15:35 UTC, cadent-dgates commented on porter/api.py
> +    if not cf.support_gzip:
As above, I'd like to keep a single return statement in this functions. It seems to make more sense to check the config in the calling function anyway.

Also, how do you feel about

1. Making this private (I'm strongly leaning towards that)
2. Renaming to `_encode_response_inplace` just to be explicit that this mutates the response object.

2020-10-12 15:59 UTC, cadent-mrichman commented on porter/api.py
> +    if not cf.support_gzip:
Agreed, see a98de0e.

2020-10-15 15:48 UTC, cadent-mrichman commented on porter/api.py
> +        if not silent:
Refactored to catch specific exceptions in one place; see 050c996.

2020-10-15 19:36 UTC, cadent-dgates commented on porter/api.py
> +        if not silent:
The refactor looks good.

2020-10-15 19:39 UTC, cadent-dgates commented on tests/test_api.py
> +        with mock.patch('flask.request', test_request(self.valid_bytes, None)):
Good thinking. Splitting up by input type keeps the number of tests short and also keeps them logically separate.

2020-10-15 21:44 UTC, cadent-dgates approved these changes

2020-10-15 21:44 UTC, merged